### ISSUE TITLE
Likely feature (todo) list

### ISSUE THREAD

**Issue by djplaner** [djplaner/canvas-collections#1]
## Required

- [x] Detect and respond to being "student view" or not
    - e.g. provide extra scaffolding in staff view etc
- [x] Use of some form of module "meta-data" to hold card meta data
- [x] What other than pre-requisites and requirements are the Canvas module specific additions / how to deal with them with cards

## Further work

- [x] if and how to include information about the items #2 
- [x] How to display collections (initially) #3
- [x] How can we store "meta-data"

**Comment by djplaner** [comment]
## Vague design

Have the view
- add a nav bar based on collections within the modules model object
- when generatingCards, only work on cards that belong to the current collection
- Modules again holding the information about the collections - based on name
