### ISSUE TITLE
Explore adoption of shoelace across the board

### ISSUE THREAD

**Issue by djplaner** [djplaner/canvas-collections#124]
## Tasks

- [x] Remember which of the details (accordions) are open in module config

## Background

Now that [shoelace](https://shoelace.style/) is successfully installed explore its application across the entire configuration interface

- [Card](https://shoelace.style/components/card) could be used in live interface as a replacement/alternative for GriffithCards
    - Main draw back would how to handle dates, coming soon, iframes etc
-  [badge](https://shoelace.style/components/badge) could be used for unpublished
- [avatar](https://shoelace.style/components/avatar) might be useful for views/users
- [breadcrumb](https://shoelace.style/components/breadcrumb) useful when moving to items
- [colorpicker](https://shoelace.style/components/color-picker) for colors
- [icon](https://shoelace.style/components/icon) as replacement for Canvas icons
- [Progress Ring]
- [QR Code] - useful for providing access to content
- [Switch](https://shoelace.style/components/switch) for the on/off button
- [tooltip](https://shoelace.style/components/tooltip) as replacement
- form elements
    - [button](https://shoelace.style/components/button)
    - dropdown
    - input
    - select
    - textarea

**Comment by djplaner** [comment]
## Remember open details module config design

Add configDetails dict entry to module's JSON, initially with "details" entry which is a dict entry for: dates, banner, metadata.  Which can be empty of open

- [ ] Do a check for configDetails and details on start up
- [ ] view modifies details settings on that basis
- [ ] event handler which changes details entry when the details are clicked (sl-show and sl-hide)
