### ISSUE TITLE
Implement an "information" object

### ISSUE THREAD

**Issue by djplaner** [djplaner/canvas-collections#127]
Idea is that an object can be specified as "information only".  i.e. it will display the information embedded by Collection's object - but not any information about the module.  Including the link to the module.

aka Coming Soon.

## Design

In module config - under "Collection" and before "description"   add

- switch to turn on "FYI only"
- unhide a textbox to enter a message

If turned on

- the message is displayed in the coming soon space
- any representation should not publish a link or any other module specific information
- it will be represented whether or not the module is published/visible to the student or not

## Tasks

- [x] View - add form element
- [x] Controller - modify module
- [x] Documentation - modify [walk thru](https://djplaner.github.io/canvas-collections/getting-started/configure/modules/)
- Views
    -  Card
        - [x] Live
        - [x] Claytons
    - Table
        - [x] Live
        - [x] Claytons

**Comment by djplaner** [comment]
## Card representation of FYI object

- Published/unpublished - don't show
- No engage button
- No link
- Enable all "noclick"
- Display fyiText as message

**Comment by djplaner** [comment]
## Claytons updating

Claytons works using the DOM - rather than the data.

Partially working

Need to move Claytons to using new styles "footer" etc.
