### ISSUE TITLE
Documentation planning

### ISSUE THREAD

**Issue by djplaner** [djplaner/canvas-collections#205]
## Tasks

- [x] Fix up all the mkdocs errors

### Update code links

- [x] CanvasCollections
- [x] ProcessImportedCollections
- [x] ModuleCofniguration
- [x] IncludePage
- [x] CollectionsNavigation
- [x] CollectionsConfiguration
- [x] CollectionRepresentation
- [x] CanvasCollectionsReprsentation
- [x] GriffithCards
- [x] CollectionsTable
- [x] CollectionsOnly
- [x] AssessmetTable
- [x] BannerColour
- [x] CannerIframe
- [x] BannerImage
- [x] dateWidget
- [x] CollectionConfiguration
- [x] ExistingCollections
- [x] FullClaytons
- [x] ModuleBannerConfiguration
- [x] ModuleDateConfiguration
- [x] ModulegeneralConfiguratoin
- [x] ModulemetaDataConfiguration
- [x] NewCollection

### Landing page

- [x] sl-tabs - make more responsive
- [ ] 

### Bigger picture

- [x] review types of documentation

## Overall design

- [x] choose new color palette
- [x] redesign logo to use that palette

## Top menu design

- Remove features & use
- Focus _Getting Started_ on installation
- Walk throughs
- Reference
- Related work
- Latest version

## Home

- [x] Bespoke HTML re-design

## Walk throughs

Standard sequence

- Turning on, visibility and (un)published
- The components of Collections
- Choosing the collections
- Choosing the representations
- Designing the objects
- Adding pages
- Generating a Claytons version

**Comment by djplaner** [comment]
## Color scheme

One
- 121212
- 304753
- f05454
- f5f5f5

**Comment by djplaner** [comment]
## latest to do - final revision
