### ISSUE TITLE
Allow, use and modify labels in Module titles

### ISSUE THREAD

**Issue by djplaner** [djplaner/canvas-collections#32]
Collections supports module's having labels with manual/auto numbering. Add an option to update the names of modules using these labels by pre-prepending ```<<label>> <<num>>: ``` to the start of Canvas module names.

## Design

In existing collections in Collections Config add a "update module names" button after the update output page

## Tasks

- [x] move default/hide colelction to just after representation
- [x] add a box around output/include page
- [x] add the update module name number
- [x] add event handler
- [ ] implement a updateModuleName controller
    - [ ] takes collectionName as the parameter and updates all the modules
        - [ ] Remove any existing label from the beginning - including different labels
            -  Maybe add a "raw name" entry into the Collections module entry as a store for the original name? Won't work as it may change
        - [x] add in the new one
        - [x] Don't add any if there is no module/label
        - [ ] Report any changes
        - [ ] Figure out if/how the updates can be made apparent to the user -- may have to do a refresh of the page
- [x] Figure out how the views are not going to include the labels in the names - maybe getModuleCollections removes them?

**Comment by djplaner** [comment]
Basic version in production. Further enhancements in new issues.
