### ISSUE TITLE
How to handle modules without a collection - display of modules /collection relationship in general

### ISSUE THREAD

**Issue by djplaner** [djplaner/canvas-collections#53]
## Design options

Should modules not allocated to a collection

- be shown in a list in the collections configuration div?  **this one***
- In a special "unallocated" collection added in staff view
    
    This would create space problems.  Probably better to do it in the collections config div

## Tasks

- [ ] add a _Module2Collection_ mapping display in canvas config
    - [ ] show all modules and the collection they belong to
    - [ ] Allow changes to collection?
    - [ ] add internal link to module config div
- [ ]  remove all radio boxes from individual collections
- [ ] add a "description" to each collection (RCE)
- [ ] Maybe add a "date available" range???? or maybe coming soon
