### ISSUE TITLE
Finalise the Module Config form

### ISSUE THREAD

**Issue by djplaner** [djplaner/canvas-collections#60]
Wide array of updates and refinements to the module config form

- [x] Copy and paste into Quill RCE
- [x] Finalise date handling  #74
- [x] Finialise coming soon handling #105 
- [x] Enable Module to be moved to unallocated to a collection
- [x] Figure out how to effectively do the preview
- [x] Auto numbering for labels  #75
- [x] Add "focus" indication
    Course search in canvas puts a red border around a input box when selected add this to collections config

**Comment by djplaner** [comment]
## Copy and paste into Quill RCE

Appears that an event handler CC adds is picking up the CTRL-V hence quill never workign.  Appears quill should perhaps work fine -- but that may be too simple

Quill currently has following event handlers added - it is set in a div
- selection-change - editorChangeHandler
- onkeydown - stopPropogation

But it is called from quillChange -- maybe this needs to be modified to handle the clipboard pasting
