### ISSUE TITLE
Fixing up dates - at least two steps

### ISSUE THREAD

**Issue by djplaner** [djplaner/canvas-collections#84]
5343law as example

- [x] add a "date label" input and handler for module config #107
- [x] Modify Griffith cards so it shortens a long day name. #108
- [x] Also us the am/pm for time - another conversion? #108
- [x] add date range support #109
